export const serviceAreas = [
  {
    slug: "restrepo",
    name: "Restrepo, Meta",
    title: "Techos y estructuras metálicas en Restrepo, Meta",
    description: "Techos, estructuras metálicas, cerramientos, pérgolas, soldadura y carpintería a medida en Restrepo, Meta, incluida la zona de Balcones de la Colina.",
    intro: "Atendemos proyectos en Restrepo, incluida la zona de Balcones de la Colina. Cuéntanos si necesitas cubrir un patio, cerrar una terraza, fabricar una estructura o aprovechar mejor un espacio con muebles a medida.",
    heading: "Preparar un techo, una pérgola o un cerramiento",
    details: [
      "Para una cubierta de patio o terraza, envía el ancho y largo aproximados, fotos de los apoyos existentes y del lugar por donde sale el agua. Estas referencias ayudan a conversar sobre pendiente, iluminación y drenaje; las medidas se verifican antes de fabricar.",
      "Si el trabajo es en Balcones de la Colina, indica el sector y cómo se accede al inmueble. Antes de coordinar una visita, revisamos contigo el alcance, la ubicación y las condiciones de ingreso de materiales.",
      "También puedes consultar por soldadura, closets, cocinas y cajoneros. En muebles, una foto del espacio y la ubicación de puertas, ventanas y tomas ayudan a definir qué distribución conviene estudiar.",
    ],
    question: "¿Se puede cotizar con fotos del patio?",
    answer: "Las fotos y medidas aproximadas permiten una primera conversación. La propuesta depende de revisar apoyos, materiales, acceso y medidas; una imagen no sustituye esa revisión.",
    checklist: ["Sector o barrio de Restrepo", "Fotos generales y de los apoyos", "Medidas aproximadas y uso del espacio", "Acceso al inmueble y disponibilidad para coordinar"],
  },
  {
    slug: "villavicencio",
    name: "Villavicencio",
    title: "Estructuras metálicas y carpintería en Villavicencio",
    description: "Estructuras metálicas, techos, soldadura y carpintería a medida en Villavicencio. Prepara medidas, fotos y condiciones de acceso para consultar tu proyecto.",
    intro: "En Villavicencio atendemos consultas de estructuras, techos, cerramientos y muebles a medida para viviendas y locales. Definimos contigo qué se necesita fabricar, instalar o revisar antes de acordar el trabajo.",
    heading: "Organizar una adecuación sin perder de vista el uso del espacio",
    details: [
      "Si el inmueble está en uso, indica qué zonas deben seguir disponibles durante el trabajo. Para un local, describe el paso de clientes, el acceso para descargar y los horarios de ingreso que permite el lugar.",
      "Para soldadura o modificaciones de una estructura existente, comparte fotos generales y de las uniones, además de explicar el cambio que buscas. La posibilidad de intervenirla se evalúa según su estado y el alcance; no se confirma capacidad de carga por una fotografía.",
      "Para closets, cocinas, cajoneros o escritorios, prepara una lista de lo que necesitas guardar o usar a diario. Revisamos distribución, apertura de puertas y cajones, materiales y acabados antes de cerrar la propuesta.",
    ],
    question: "¿Qué debo informar si la instalación es en un conjunto o local?",
    answer: "Indica barrio, piso, acceso de materiales y restricciones de la administración. Con esa información se puede coordinar la revisión y acordar las condiciones de instalación y desplazamiento.",
    checklist: ["Barrio y tipo de inmueble", "Uso actual de la zona a intervenir", "Fotos, medidas y cambios deseados", "Restricciones de acceso o de administración"],
  },
  {
    slug: "bogota",
    name: "Bogotá",
    title: "Metalmecánica y carpintería a medida en Bogotá",
    description: "Techos, cerramientos, estructuras metálicas y carpintería a medida en Bogotá. Consulta alcance, desplazamiento y condiciones de instalación para tu proyecto.",
    intro: "Recibimos consultas de proyectos en Bogotá de metalmecánica y carpintería a medida. Para coordinar el trabajo, primero revisamos ubicación, dimensiones, alcance y condiciones de desplazamiento e instalación.",
    heading: "Coordinar fabricación, transporte e instalación",
    details: [
      "En apartamentos y edificios, mide de forma orientativa puertas, escaleras y ascensor. Esos accesos influyen en el tamaño de las piezas que se pueden transportar y en cómo se organiza el montaje de armarios, cocinas o escritorios.",
      "Para techos, pérgolas o cerramientos de terraza, explica si el área es privada o compartida y qué autorizaciones o restricciones ha indicado la administración. Estos datos se revisan antes de acordar una intervención.",
      "Comparte localidad, barrio y piso para conversar sobre logística. La visita, el transporte, las fechas y sus costos se acuerdan según cada proyecto; no se presupone una visita gratuita ni una fecha inmediata.",
    ],
    question: "¿Cómo iniciar una cotización antes de coordinar una visita?",
    answer: "Envía fotos del espacio y del recorrido de acceso, medidas aproximadas y una descripción del resultado que buscas. Después se define qué información falta y cómo verificar las medidas para preparar la propuesta.",
    checklist: ["Localidad, barrio y piso", "Medidas del espacio y del recorrido de acceso", "Fotos y referencias del resultado deseado", "Condiciones de administración y fechas deseadas"],
  },
] as const;
