import assert from "node:assert/strict";
import { existsSync, readFileSync, statSync } from "node:fs";
import { test } from "node:test";
import { posts } from "../src/content/blog/posts.ts";
import { serviceAreas } from "../src/lib/service-areas.ts";
import { formatBlogDate } from "../src/lib/blog-date.ts";

const appRoot = new URL("../src/app/", import.meta.url);
const sitemap = readFileSync(new URL("../public/sitemap.xml", import.meta.url), "utf8");

test("blog slugs are unique and safe for static routes", () => {
  assert.ok(posts.length > 0);
  assert.equal(new Set(posts.map((post) => post.slug)).size, posts.length);
  for (const post of posts) assert.match(post.slug, /^[a-z0-9]+(?:-[a-z0-9]+)*$/);
});

test("the blog index and every post are in the static sitemap", () => {
  assert.ok(sitemap.includes("<loc>https://rbsoluciones.co/blog/</loc>"));
  for (const post of posts) {
    assert.ok(sitemap.includes(`<loc>https://rbsoluciones.co/blog/${post.slug}/</loc>`), post.slug);
  }
});

test("every related service resolves to an existing app route folder", () => {
  for (const post of posts) {
    for (const { href } of post.relatedServices) {
      assert.match(href, /^\/(?:[a-zA-Z0-9-]+\/)+$/);
      let route = href.slice(1);
      const municipality = /^cobertura\/([^/]+)\/$/.exec(route);
      // Coverage URLs are generated by the existing [municipio] route.
      if (municipality) {
        assert.ok(serviceAreas.some((area) => area.slug === municipality[1]), href);
        route = "cobertura/[municipio]/";
      }
      const directory = new URL(route, appRoot);
      assert.ok(existsSync(directory), `Missing route folder: ${href}`);
      assert.ok(statSync(directory).isDirectory(), href);
      assert.ok(existsSync(new URL("page.tsx", directory)), `Missing page: ${href}`);
    }
  }
});

test("publication dates use Colombian formatting without shifting the day", () => {
  assert.equal(formatBlogDate("2026-09-27"), "27 de septiembre de 2026");
});
